name: Infrastructure Deployment

on:
  push:
    paths:
      - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: cd infrastructure/cdk && npm i

    - name: Synth
      run: cd infrastructure/cdk && npx cdk synth

    - name: Deploy
      run: cd infrastructure/cdk && npx cdk deploy --require-approval
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
