name: Infrastructure Deployment

on:
  push:
    paths:
      - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: cd infrastructure/cdk && npm i

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2'

    - name: Synth
      run: cd infrastructure/cdk && cdk synth BackendStack

    - name: Deploy
      run: cd infrastructure/cdk && cdk deploy BackendStack --require-approval never
